.github/workflows/nightly.yml
Cargo.lock
Cargo.toml
README.md
src/cli/mod.rs
src/subcommands/psa_export_key.rs

Signed-off-by: Hugues de Valon <hugues.devalon@arm.com>

Upgrade dependencies

---

Cargo.toml
src/subcommands/list_keys.rs
src/subcommands/mod.rs

Signed-off-by: Joe Ellis <joe.ellis@arm.com>

Add list-keys subcommand

---

Cargo.lock
Cargo.toml

Remove unused anyhow

---

src/cli/mod.rs
src/subcommands/common.rs
src/subcommands/list_opcodes.rs

Replace default_value with Option

---

src/subcommands/create_ecc_key.rs
src/subcommands/create_rsa_key.rs
src/subcommands/decrypt.rs
src/subcommands/delete_client.rs
src/subcommands/delete_key.rs
src/subcommands/encrypt.rs
src/subcommands/export_key.rs
src/subcommands/export_public_key.rs
src/subcommands/generate_random.rs
src/subcommands/list_authenticators.rs
src/subcommands/list_clients.rs
src/subcommands/list_keys.rs
src/subcommands/list_opcodes.rs
src/subcommands/list_providers.rs
src/subcommands/mod.rs
src/subcommands/ping.rs
src/subcommands/sign.rs
src/subcommands/verify.rs

Fix #26 
It is based on PR #32 
Also start some work for #32 and #27 by creating the template files. They are obviously wrong now but can be changed when tackling those issues.
(just focus on the second commit for the review)

Rename things with more friendly names

---

README.md
tests/ci.sh
tests/expected_output/list-keys

Specify format of public keys in README

---

CHANGELOG.md

Signed-off-by: Hugues de Valon <hugues.devalon@arm.com>

Update the CHANGELOG file

---

.cargo/audit.toml

Add the same config file already present in the service repo.

Add cargo-audit config file

---

Cargo.lock
Cargo.toml

Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>

Bump version to 0.4.0

---

CHANGELOG.md

Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>

Update CHANGELOG.md with 0.4.0 details

---

Cargo.lock
Cargo.toml

Also performs a `cargo update`

Upgrade client's version

---

tests/parsec-cli-tests.sh

Fixes #66 
Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>

Avoid using pipes to run all test commands in the same sub-shell

---

tests/parsec-cli-tests.sh

- Fix key type in some print lines
- Print CSR deatils in debug mode only
Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>

Small output fixes

---

Cargo.lock
Cargo.toml

Prepare to release new version

---

.cargo/audit.toml
Cargo.lock
Cargo.toml
SECURITY.md

Update dependencies that have been yanked

---

CHANGELOG.md

Update changelog for 0.5.x

---

CHANGELOG.md

Signed-off-by: Mohamed Omar Asaker <mohamed.omarasaker@arm.com>

Update Chanege log for the release 0.5.3

---

CHANGELOG.md
Cargo.toml

Change version to 0.5.4 and update the changelog

Create 0.5.4 point release

---

.cargo/audit.toml
Cargo.lock

The MR has the following changes:
- Fix cargo audit failure
- Update lock file to reflect the toml changes

Fix nightly CI and update lock

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Update changelog and crate version

---

Cargo.lock
Cargo.toml

Signed-off-by: Tomás González <tomasagustin.gonzalezorlando@arm.com>

Remove unused atty dependency

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Update crate version and add changelog

---

.github/actions/ci_script/action.yml
.github/workflows/ci.yml
tests/ci.sh

Signed-off-by: Tomás González <tomasagustin.gonzalezorlando@arm.com>

ci.yml,ci.sh: Create parallel jobs for stable and MSRV
