src/cli/mod.rs
src/main.rs
src/subcommands/mod.rs

It makes more sense there.
Signed-off-by: Joe Ellis <joe.ellis@arm.com>

Move subcommand dispatching to `Subcommand` enum

---

src/subcommands/list_providers.rs

We now label the field as 'UUID', as we should.

List providers UUID fix

---

README.md

Hey guys,
I've added an `asciinema` demo to the repository, as suggested in issue #2. The demo video is linked below:
[![asciicast](https://asciinema.org/a/352154.svg)](https://asciinema.org/a/352154)
You can, of course, see how this looks in the context of the `README.md` file by taking a look at my fork. 😄 
Cheers!

Add asciinema demo

---

src/subcommands/mod.rs
src/subcommands/psa_destroy_key.rs
src/subcommands/psa_generate_key.rs

The Generate key one currently hardcodes the key to 2048 bits RSA to make it easier to use on the CLI.
I tested it and it works well 😄 
```
[hugdev01@machine parsec-tool]$ ./target/debug/parsec-tool -a tata psa-generate-key -k toto -p 1
[INFO] Generating key...
[hugdev01@machine parsec-tool]$ ./target/debug/parsec-tool -a tata psa-export-public-key -k toto -p 1
[INFO] Exporting public key...
[SUCCESS] Key:
30 82 01 0A 02 82 01 01 00 CF 35 30 8A C6 11 B0 F3 C8 5C 4C 80 46 D7 EE BD 14 20 10 C6 E4 07 0D 83 63 79 B9 36 1C 0D 8D 1C E2 CB 0F 0E CC 33 F8 F0 B2 28 AC 3F B8 A2 B9 1E BC 98 6B 74 95 D6 34 34 74 90 73 72 80 C8 0C 3C CF BF 8A A7 5B C2 30 68 B3 DE 06 75 01 27 30 AE CC 3C AC 7F B8 B5 01 0E 2D 61 32 BD 18 D1 FC B2 C4 D3 12 61 72 B0 C0 19 19 C7 BF 1E BE C2 97 C8 FA 70 9F 7E 52 90 07 8D B9 …
```

Add the generate and destroy key operations

---

.gitignore
Cargo.lock
Cargo.toml
src/cli/mod.rs
src/subcommands/common.rs
src/subcommands/list_keys.rs
src/subcommands/list_opcodes.rs
src/subcommands/list_providers.rs
src/subcommands/ping.rs
src/subcommands/psa_destroy_key.rs
src/subcommands/psa_export_key.rs
src/subcommands/psa_export_public_key.rs
src/subcommands/psa_generate_key.rs
src/subcommands/psa_generate_random.rs

This commit changes the way the provider and authentication is chosen
for each command by using the bootstrapping functionality implemented in
the client.

Make use of client bootstrapping functionality

---

src/subcommands/list_authenticators.rs
src/subcommands/list_opcodes.rs
src/subcommands/list_providers.rs
src/subcommands/mod.rs
src/subcommands/ping.rs

Also remove authentication for Core operations that do not need it.
Signed-off-by: Hugues de Valon <hugues.devalon@arm.com>

Add list-authenticators subcommand

---

Cargo.lock
Cargo.toml
src/subcommands/delete_client.rs
src/subcommands/list_clients.rs
src/subcommands/mod.rs

Add ListClients and DeleteClient operations

---

src/cli/mod.rs
src/main.rs
src/subcommands/create_ecc_key.rs
src/subcommands/create_rsa_key.rs
src/subcommands/decrypt.rs
src/subcommands/delete_client.rs
src/subcommands/delete_key.rs
src/subcommands/encrypt.rs
src/subcommands/export_key.rs
src/subcommands/export_public_key.rs
src/subcommands/generate_random.rs
src/subcommands/list_authenticators.rs
src/subcommands/list_clients.rs
src/subcommands/list_keys.rs
src/subcommands/list_opcodes.rs
src/subcommands/list_providers.rs
src/subcommands/mod.rs
src/subcommands/ping.rs
src/subcommands/sign.rs
src/subcommands/verify.rs

This commit adds an instance of BasicClient to the ParsecToolApp so that
all subcommands can simply use this one instead of spinning up their
own.

Add BasicClient to ParsecToolApp

---

Cargo.lock
Cargo.toml
src/subcommands/export_public_key.rs

This commit modifies the export public key operation to format the
output as PEM. Depending on the "output" flag, the result is either
printed to stdout or written to a file.
Close #28

Format public key to PEM

---

Cargo.lock
Cargo.toml
README.md
src/cli/mod.rs
src/main.rs

Adds a way to change the client's timeout on the command line.

Add a timeout CLI option

---

Cargo.lock
Cargo.toml

We already tagged `0.1.0` and `0.2.0`.

Prepare for 0.3.0 release

---

src/subcommands/list_opcodes.rs
tests/ci.sh
tests/expected_output/list-keys

list_opcodes needs a provider as a parameter. This change makes the
provider parameter optional so that, when not given, it will use the
default provider instead.
Fix #53

Use the implicit provider for list_opcodes

---

Cargo.lock
Cargo.toml
README.md
src/subcommands/create_ecc_key.rs
src/subcommands/create_rsa_key.rs
src/subcommands/decrypt.rs
src/subcommands/delete_client.rs
src/subcommands/delete_key.rs
src/subcommands/export_public_key.rs
src/subcommands/sign.rs
tests/ci.sh

I choose the version `0.3.1` as the CLI interface did not change in a breaking way since `0.3.0`.
Added the `spiffe-auth` feature in case people want to use it (if that is the default one).
Also updated the asciinema demo 📽️ 
Fix #44

Prepare for the next release

---

Cargo.lock
Cargo.toml
src/error.rs
src/lib.rs
src/subcommands/create_csr.rs
src/subcommands/mod.rs
src/subcommands/sign.rs
src/util.rs
tests/parsec-cli-tests.sh

- Refactors the majority of the `sign` command into a new `util` module so that it can be shared, because signing for a CSR is essentially the same operation.
- Introduce the `create-csr` command, which uses the `rcgen` crate (a new dependency with dual MIT/Apache-2 license)
- Fixes the CLI test script so that it works on MacOS as well as Linux, and adds a rudimentary test case for the new command, using `openssl` to check the validity of the certificate request document

Early support for certificate request generation in parsec-tool

---

src/subcommands/create_ecc_key.rs
src/subcommands/create_rsa_key.rs
tests/parsec-cli-tests.sh

Use either `--for-signing` or `-s` on the command line to `create-rsa-key` in order to switch it over to creating a signing key.

Support the creation of RSA signing keys as well as encryption keys

---

Cargo.lock
Cargo.toml
src/subcommands/decrypt.rs

Catching up to date with the latest release of `rcgen`.
Also fixing a clippy lint issue.

Update version of `rcgen` we use

---

src/subcommands/encrypt.rs
src/subcommands/mod.rs
tests/parsec-cli-tests.sh

Makes it possible to use `parsec-tool` for encryption (with a public key or the public part of a key pair). The purpose of this is that it enables a use case where asymmetric encryption workflows can be round-tripped using only `parsec-tool` without any dependencies on third-party tools. This is useful for demonstration purposes.
The code is essentially a mirror-image of the existing `decrypt` command. It produces base64 output by default, which can be entered directly into `decrypt` to recover the original string.
Test case added to the CLI script. Note that the existing test_encryption function has been re-named to test_decryption, and I have introduced a new test_encryption function so that all of the nomenclature matches up.

Add an encrypt command plus tests.

---

src/subcommands/create_csr.rs
tests/parsec-cli-tests.sh

Support serialNumber field of Distinguished Name for CSRs.
This is useful for the identification of individual devices in onboarding scenarios.

Support serialNumber field of Distinguished Name for CSRs.

---

src/subcommands/create_rsa_key.rs
tests/parsec-cli-tests.sh

Support a 'bits' argument for specifying the size/strength of RSA keys.

Support a 'bits' argument for specifying the size/strength of RSA keys.

---

tests/parsec-cli-tests.sh

Different OpenSSL versions provide different strings when the public key is exported. Some versions have 'RSA Public-Key' and some only 'Public-Key'. This commit changes the grepped string to make the test generic.
Closes #90 

Make RSA key string generic

---

src/lib.rs

This PR only removed `const_err` since it will be a hard error in future: https://github.com/rust-lang/rust/issues/71800

Update lib.rs to remove const_err

---

Cargo.lock

For packaging parsec service and the parsec tool to different distributions, it is ideal to have crate versions aligned so that multiple versions of the same crate are not included. To achieve this, the lock file has been updated by running cargo update generic and also precisely to a particular version for a few crates.

Align crates version with parsec-service

---

Cargo.lock
Cargo.toml

The 'ansi_term' crate is currrently being flagged as unmaintained. The dependency tree that is bringing this crate is:
ansi_term 0.12.1
└── clap 2.34.0
└── structopt 0.3.26
└── parsec-tool
ansi_term is an optional dependency that we are bringing along.
* Remove this and other optional dependencies by disabling the default-features for structopt.

Disable structopt default features

---

tests/ci.sh
tests/parsec-cli-tests.sh

This flag can be used for testing parsec on slower platforms where RSA 2048 key operations are time consuming.
Closes #112

Add RSA_KEY_SIZE flag to cli test script

---

.github/actions/ci_script/action.yml
.github/workflows/nightly.yml
tests/ci.sh
utils/dependency_cross_matcher.py

- Add a script to check for mismatches in dependencies in the repository.
- Add a dependency mismatcher job that checks whether any dependencies have more than one versions.
Mismatches are two different versions of the same dependency.
This is based (almost a complete duplication) on what we currently have in Parsec:
https://github.com/parallaxsecond/parsec/pull/731

Add dependency cross matching

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
Cargo.lock
tests/ci.sh
utils/dependency_cross_matcher.py

Depends on #115 . Please only review when this one is merged.
- Compare dependencies between parsec and parsec-tool to spot common dependencies that are being used with different versions.
- Incorporate a nightly check to test this
Closes https://github.com/parallaxsecond/parsec/issues/360

ci/nightly: Compare parsec and parsec-tool dependency versions

---

.github/workflows/nightly.yml
tests/ci.sh

parsec-tool depends on several repositories under the parallaxsecond organization.
Currently, when testing the main branch of parsec, fixed versions of the latest released crates of those repositories are being used.
A problem may arise when there is a change introduced in the main/'test-next' branch of those repositories that would break parsec when updating/incorporating that change. This is currently not being tested in our CI.
As parsec-tool release is dependent on having published the dependencies' crates, there are issues that will not be caught until the publishing of said crates.
Add nightly jobs that use ci.sh --test-next-branch-tracking to test the next release branches of parallaxsecond repositories and spot issues before release. These jobs makes use of parsec's …

Track and test dependencies' 'test-next' branch

---

tests/parsec-cli-tests.sh

openssl 3.2.0 from yocto prints serialNumber to output without spaces so support both that and the old with spaces output to pass the test. Not using regular
expressions to work on simpler grep implementations.

parsec-cli-tests.sh: adapt to new serialNumber output

---

.github/workflows/nightly.yml

shlex is currently only being brought by bindgen, which does not use the concerning APIs except for testing.

ci: Ignore shlex report

---

clippy.toml
src/subcommands/create_csr.rs
src/subcommands/create_rsa_key.rs
tests/parsec-cli-tests.sh

Add support for RSA-PSS

---

.gitignore
Cargo.lock
Cargo.toml
patches/rcgen+0.9.3.patch
src/subcommands/create_csr.rs
tests/ci.sh

RSA-PSS CSR creation functionality has been recently added.
For creating the CSRs, we are currently using rcgen.
For RSA-PSS, rcgen defined the PKCS_RSA_PSS_SHA256 type, which should be used instead of the currently used one (PKCS_RSA_SHA256).
Unfortunately, rcgen does not expose this type as there have been some issues validating the CSR creation of this type.
This has been tested using real RSA PSS keys and the functionality works as expected.
* Patch rcgen to expose the PKCS_RSA_PSS_SHA256 type. The patch applies until these changes get fixed/merged upstream
in rcgen.
* Use this type in parsec-tool CSR creation for RSA-PSS.

Cargo.toml: Temporary patch rcgen crate for RSA-PSS CSR support
